<a href="https://colab.research.google.com/github/leoafs/DIP/blob/main/TutorialNP_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Array**

In [42]:
import numpy as np


* How to create an empty and a full NumPy array?



In [ ]:
a = np.empty(shape=2)
print("Empty")
print(a)

b = np.full([3, 3], 55)
print("FULL")
print(b)

Empty
[4.65919951e-310 0.00000000e+000]
FULL
[[55 55 55]
 [55 55 55]
 [55 55 55]]


* Create a Numpy array filled with all zeros

In [ ]:
zeros=np.zeros((5,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


* Create a Numpy array filled with all ones


In [ ]:
ones=np.ones((5,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


* Check whether a Numpy array contains a specified row


In [ ]:
num = np.arange(10)
arr1 = np.reshape(num, [5, 2])
print("Original array:")
print(arr1)
print([0, 1] in arr1.tolist())
print([0,2] in arr1.tolist())
print([1,1] in arr1.tolist())

Original array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
True
False
False


* How to Remove rows in Numpy array that contains non-numeric values?


In [ ]:
a = np.array([[10.5, 22.5, np.nan],
                  [41, 52.5, 1],[1 , 1 ,1]])
a[~np.isnan(a).any(axis=1)]
print(a[~np.isnan(a).any(axis=1)])

[[41.  52.5  1. ]
 [ 1.   1.   1. ]]



* Remove single-dimensional entries from the shape of an array




In [ ]:
x = np.zeros((3, 1, 4,3,1,6))
print(np.squeeze(x).shape)



(3, 4, 3, 6)


* Find the number of occurrences of a sequence in a NumPy array


In [54]:
a = np.array([[2, 1, 9, 1], [8, 5, 9, 1],[9, 4, 9, 1],[4, 9, 4, 5],[9, 4, 9, 4]])
  
p= repr(a).count("9, 4")
  
print(p)

4


* Find the most frequent value in a NumPy array

In [62]:
x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(x)
y = np.bincount(x)
m = max(y)  
print()
for i in range(len(y)):
    if y[i] == m:
        print(i, end=" ")

[1 1 1 2 3 4 2 4 3 3]

1 3 

* Combining a one and a two-dimensional NumPy Array

In [64]:
Array1d = np.arange(5)
print(Array1d)
  
Array2d = np.arange(10).reshape(2,5)
print(Array2d)
for a, b in np.nditer([Array1d, Array2d]):
    print("%d:%d" % (a, b),)

[0 1 2 3 4]
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


* How to build an array of all combinations of two NumPy arrays?

In [67]:
array1 = np.array([3, 2])
array2 = np.array([1, 4])
  
print("Array1")
print(array1)
  
print("\nArray2")
print(array2)

comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
  
print("\nCombine array:")
print(comb_array)

Array1
[3 2]

Array2
[1 4]

Combine array:
[[3 1]
 [3 4]
 [2 1]
 [2 4]]


* How to add a border around a NumPy array?

In [71]:
a = np.ones((4, 4))
print(a)

a = np.pad(a, pad_width=1, mode='constant',
               constant_values=0)
  
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


* How to compare two NumPy arrays?


In [77]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

comparison = b == b
print(comparison)
equal_arrays = comparison.all()
print(equal_arrays)


[[ True  True]
 [ True  True]]
True


* How to check whether specified values are present in NumPy array?

In [81]:
a = np.array([[1, 4, 0],[3, 1, 4]])
print(2 in a)
print(0 in a)
print(6 in a)
print(50 in a)
print(4 in a)

False
True
False
False
True


* How to get all 2D diagonals of a 3D NumPy array?

In [83]:
arr = np.arange(3 * 4 * 4).reshape(3, 4, 4)
print(arr)

diag_arr = np.diagonal(arr, 
                       axis1 = 1,
                       axis2 = 2)
  
print("2d diagonal array:\n", 
      diag_arr)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
2d diagonal array:
 [[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


* Flatten a Matrix in Python using NumPy

In [89]:
a=np.array([[1,2],[2,3]])
print(a.flatten())


[1 2 2 3]


* Flatten a 2d numpy array into 1d array

In [90]:
a=np.array([[1,2],[2,3],[1 , 1]])
print(a.flatten())

[1 2 2 3 1 1]


* Move axes of an array to new positions

In [94]:
a = np.zeros((1, 2, 3, 4))
  
b = np.moveaxis(arr, 0, -1).shape
  
print (b)

(2, 3, 4, 1)


* Interchange two axes of an array

In [95]:
x = np.array([[1,2,3]])
print(x)
y =  np.swapaxes(x,0,1)
print(y)

[[1 2 3]]
[[1]
 [2]
 [3]]


* NumPy – Fibonacci Series using Binet Formula

In [97]:
a = np.arange(1, 11)
lengthA = len(a)
sqrtFive = np.sqrt(5)
alpha = (1 + sqrtFive) / 2
beta = (1 - sqrtFive) / 2
Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrtFive))
print("os primeiros {} valores da série{} . ".format(lengthA, Fn))

os primeiros 10 valores da série[ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.] . 


* Counts the number of non-zero values in the array

In [102]:
a = [[0, 1, 2, 0, 0], [0, 4, 0, 0, 1]]
  
b = np.count_nonzero(a)
  
print (b) 

4


* Count the number of elements along a given axis


In [103]:
a = np.array([[1, 22, 41, 41], [3, 6,47, 1]])
print(np.size(a))

8


* Trim the leading and/or trailing zeros from a 1-D array

In [106]:
a = np.array ((0, 0, 0, 7, 2, 3, 7, 4, 2, 0))
print(np.trim_zeros (a))

[7 2 3 7 4 2]


* Change data type of given numpy array

In [114]:
a = np.ones([2,2])
print(a)
print(a.dtype)
a=a.astype('int')
print(a)
print(a.dtype)


[[1. 1.]
 [1. 1.]]
float64
[[1 1]
 [1 1]]
int64


* Reverse a numpy array

In [122]:
a= np.array([1, 2, 3,4, 5])
  
print(a)
 
b = a[::-1]
  
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


* How to make a NumPy array read-only?

In [128]:
a = np.zeros(11)
print("antes ")
print(a)
print( "depois")
a[0]=1
print(a)
print("antes")
a.flags.writeable = False
print(a)
print("depois")
a[1]=2

antes 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
depois
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
antes
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
depois


ValueError: ignored

**Questions on NumPy Matrix**

* Get the maximum value from given matrix

In [133]:
a=np.array([[1,2,5,4,3],[1,1,10,5,3]])
b=np.max(a)
print(b)

10


* Get the minimum value from given matrix

In [135]:
a=np.array([[-1,2,5,4,3],[1,1,10,5,3]])
b=np.min(a)
print(b)

-1


* Find the number of rows and columns of a given matrix using NumPy

In [147]:
a=np.array([[10,11,12,13],[14,15,16,17],[18,19,20,21]])
print(a)
print(a.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
(3, 4)


* Select the elements from a given matrix



* Find the sum of values in a matrix

In [166]:
a=np.array([[1,2],[2,3]])
print('A')
print(a)
print("Soma")
b=a.sum()
print(b)


A
[[1 2]
 [2 3]]
Soma
8


* Calculate the sum of the diagonal elements of a NumPy array

In [169]:
a=np.array([[1,2],[2,3]])
b=a.diagonal()
print(b)
print(b.sum())

[1 3]
4


* Adding and Subtracting Matrices in Python

In [171]:
a=np.array([[1,2],[2,3]])
b=np.array([[1,4],[1,3]])
print(a)
print(b)
c=a+b
d=a-b
print("sum")
print(c)
print("sub")
print(d)


[[1 2]
 [2 3]]
[[1 4]
 [1 3]]
sum
[[2 6]
 [3 6]]
sub
[[ 0 -2]
 [ 1  0]]


* Ways to add row/columns in numpy array

In [191]:
a=np.array([[1,2],[2,3]])
print(a)
b=np.array([17,8])
print(b)
a=np.vstack([a,b])
print(a)

[[1 2]
 [2 3]]
[17  8]
[[ 1  2]
 [ 2  3]
 [17  8]]


* Matrix Multiplication in NumPy

In [192]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[9,8,7,6],[5,4,3,3],[2,1,2,0]])

m3 = np.matmul(m1,m2)
print(m3)

[[ 25  19  19  12]
 [ 73  58  55  39]
 [121  97  91  66]]


* Get the eigen values of a matrix

* How to Calculate the determinant of a matrix using NumPy?

* How to inverse a matrix using NumPy

* How to count the frequency of unique values in NumPy array?

* Multiply matrices of complex numbers using NumPy in Python

* Compute the outer product of two given vectors using NumPy in Python

* Calculate inner, outer, and cross products of matrices and vectors using NumPy

* Compute the covariance matrix of two given NumPy arrays

* Convert covariance matrix to correlation matrix using Python

* Compute the Kronecker product of two mulitdimension NumPy arrays

* Convert the matrix into a list